# Default virtual keyboard layout (Termux style)
extra-keys=[ ['ESC','<','>','/','\=','^','$','()','{}','[]','ENTER'], ['\!','?','@','\#',',','(',')','[',']','{','}'], ['TAB','&',';','/','~','%','*','HOME','UP','END','PGUP'], ['CTRL','FN','ALT','|','-','+','"','LEFT','DOWN','RIGHT','PGDN'] ]
